USE tempdb
GO

DROP TABLE IF EXISTS dbo.PRODUCT_DETAILS; 
DROP TABLE IF EXISTS dbo.UPDATE_DETAILS;

CREATE TABLE PRODUCT_DETAILS (
    P_ID int,
    P_NAME varchar(255),
    P_PRICE FLOAT 
);

SELECT * INTO UPDATE_DETAILS FROM PRODUCT_DETAILS;

BULK INSERT PRODUCT_DETAILS FROM 'E:\Sandipan\ReadingMaterials\sql\data\PRODUCT_DETAILS.csv'
   WITH (
      FIELDTERMINATOR = ',',
      ROWTERMINATOR = '\n'
);
GO

BULK INSERT UPDATE_DETAILS FROM 'E:\Sandipan\ReadingMaterials\sql\data\UPDATE_DETAILS.csv'
   WITH (
      FIELDTERMINATOR = ',',
      ROWTERMINATOR = '\n'
);
GO

SELECT * FROM PRODUCT_DETAILS;
SELECT * FROM UPDATE_DETAILS


MERGE PRODUCT_DETAILS AS TARGET
	USING UPDATE_DETAILS AS SOURCE 
		ON (TARGET.P_ID = SOURCE.P_ID)

	WHEN MATCHED AND TARGET.P_NAME <> SOURCE.P_NAME 
				 OR TARGET.P_PRICE <> SOURCE.P_PRICE THEN 
	UPDATE SET	TARGET.P_Name = SOURCE.P_NAME,
				TARGET.P_PRICE = SOURCE.P_PRICE --if there are changes in P_NAME OR P_PRICE
	
	WHEN NOT MATCHED BY TARGET THEN  
	INSERT (P_ID,P_NAME,P_PRICE)
	VALUES (SOURCE.P_ID,SOURCE.P_NAME,SOURCE.P_PRICE)

	WHEN NOT MATCHED BY SOURCE THEN         
	DELETE; 

SELECT * FROM PRODUCT_DETAILS;

